// @krishi-verse/tokens · GENERATED from designer_pack/tokens/design-tokens.json — DO NOT HAND-EDIT.
// Regenerate: node sync-from-design-system.js (source generated by hand1_tokens_export.py,
// which itself parses system/tokens.css + system/web/web-tokens.css — the true canon).
// Batch HAND-1, 2026-07-22. Supersedes the pre-HAND-1 placeholder palette/font-stack,
// which did not correspond to canon at all (zero consumers existed at time of correction,
// grep-verified against krishi-verse/ — see hand1_report.md).
export const spacing = {
  '0': "0",
  '1': "0.25rem",
  '2': "0.5rem",
  '3': "0.75rem",
  '4': "1rem",
  '5': "1.25rem",
  '6': "1.5rem",
  '8': "2rem",
  '10': "2.5rem",
  '12': "3rem",
  '16': "4rem",
  '20': "5rem",
  '24': "6rem",
} as const;
export const radii = {
  sm: "0.375rem",
  md: "0.625rem",
  lg: "0.875rem",
  xl: "1.25rem",
  '2xl': "1.75rem",
  full: "9999px",
} as const;
// NOTE: canon has no dedicated --bp-* custom properties (checked this batch — the
// breakpoint figures documented in system/web/web-tokens.css are a PROSE COMMENT, not
// live tokens; real breakpoints are literal numbers inside @media rules: console
// 768/1024/1440, storefront 360/768/1440). Kept here as the nearest literal values so
// downstream code has SOMETHING to import; flagged ENGINEERING-OWED if a real --bp-*
// custom-property set should be added to system/web/web-tokens.css upstream instead.
export const breakpoints = { sm: '360px', md: '768px', lg: '1024px', xl: '1440px' } as const;
// Minimum tap targets (contract §8 / tokens.css --tap-*). touchTargetMinPx keeps the prior
// export's name for import-compatibility; value corrected to canon's --tap-min (44px).
export const touchTarget = {
  min: "44px",
  rural: "48px",
  large: "56px",
} as const;
export const touchTargetMinPx = 44;
