// @krishi-verse/tokens · GENERATED from designer_pack/tokens/design-tokens.json — DO NOT HAND-EDIT.
// Regenerate: node sync-from-design-system.js (source generated by hand1_tokens_export.py,
// which itself parses system/tokens.css + system/web/web-tokens.css — the true canon).
// Batch HAND-1, 2026-07-22. Supersedes the pre-HAND-1 placeholder palette/font-stack,
// which did not correspond to canon at all (zero consumers existed at time of correction,
// grep-verified against krishi-verse/ — see hand1_report.md).
export const fontFamily = {
  display: "'Fraunces', 'Hind', Georgia, serif",
  body_en: "'Plus Jakarta Sans', 'Hind', system-ui, -apple-system, sans-serif",
  body_hi: "'Hind', 'Plus Jakarta Sans', system-ui, sans-serif",
  body_gu: "'Hind Vadodara', 'Plus Jakarta Sans', system-ui, sans-serif",
  mono: "'JetBrains Mono', 'Fira Code', Consolas, monospace",
} as const;
export const fontSize = {
  xs: "0.75rem",
  sm: "0.875rem",
  base: "1rem",
  lg: "1.125rem",
  xl: "1.25rem",
  '2xl': "1.5rem",
  '3xl': "1.875rem",
  '4xl': "2.25rem",
  '5xl': "3rem",
  '6xl': "3.75rem",
} as const;
export const fontWeight = {
  regular: 400,
  medium: 500,
  semibold: 600,
  bold: 700,
  extrabold: 800,
} as const;
export const lineHeight = {
  tight: 1.1,
  snug: 1.25,
  normal: 1.5,
  relaxed: 1.65,
} as const;
// Senior-mode type-scale multiplier (BRAND-026, G0-2 Q48 ratified). Multiply any
// base fontSize value by this constant when Senior Mode is active (mobile app only —
// see designer_pack/07-developer-handoff.md's Scoping Mechanisms section).
export const seniorModeTypeScaleMultiplier = 1.30;
