# infra/terraform/modules/aurora/main.tf · Aurora PostgreSQL 16 Serverless v2 (writer + reader), encrypted, PITR
#
# Security posture (non-negotiable, independent of cost tier):
#   - storage encrypted with a customer KMS key
#   - master password generated + stored in Secrets Manager (manage_master_user_password)
#   - lives ONLY in isolated data subnets, no public access
#   - 5432 reachable only from explicitly-allowed SGs (EKS nodes)
#   - PITR via backup_retention_period >= 7d, deletion protection on
#   - statement_timeout / lock_timeout enforced at the DB

terraform {
  required_version = ">= 1.6.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.60"
    }
  }
}

locals {
  tags   = merge(var.tags, { "Module" = "aurora" })
  family = "aurora-postgresql16"
}

resource "aws_db_subnet_group" "this" {
  name       = "${var.name}-aurora"
  subnet_ids = var.data_subnet_ids
  tags       = local.tags
}

resource "aws_security_group" "this" {
  name        = "${var.name}-aurora"
  description = "Aurora PostgreSQL access"
  vpc_id      = var.vpc_id
  tags        = merge(local.tags, { Name = "${var.name}-aurora" })
}

resource "aws_security_group_rule" "ingress" {
  count                    = length(var.allowed_security_group_ids)
  type                     = "ingress"
  from_port                = 5432
  to_port                  = 5432
  protocol                 = "tcp"
  security_group_id        = aws_security_group.this.id
  source_security_group_id = var.allowed_security_group_ids[count.index]
  description              = "PostgreSQL from allowed SG"
}

resource "aws_security_group_rule" "egress" {
  type              = "egress"
  from_port         = 0
  to_port           = 0
  protocol          = "-1"
  security_group_id = aws_security_group.this.id
  cidr_blocks       = ["0.0.0.0/0"]
  description       = "all egress"
}

# Cluster parameter group: enforce timeouts + force TLS
resource "aws_rds_cluster_parameter_group" "this" {
  name        = "${var.name}-aurora-pg16"
  family      = local.family
  description = "Krishi-Verse Aurora PG16 cluster params"
  tags        = local.tags

  parameter {
    name  = "rds.force_ssl"
    value = "1"
  }
  parameter {
    name  = "statement_timeout"
    value = tostring(var.statement_timeout_ms)
  }
  parameter {
    name  = "lock_timeout"
    value = tostring(var.lock_timeout_ms)
  }
  parameter {
    name  = "log_min_duration_statement"
    value = "1000"
  }
}

resource "aws_rds_cluster" "this" {
  cluster_identifier = "${var.name}-aurora"
  engine             = "aurora-postgresql"
  engine_mode        = "provisioned"
  engine_version     = var.engine_version
  database_name      = var.database_name
  master_username    = var.master_username

  # Master password is generated by AWS and stored in Secrets Manager — never in TF state as plaintext.
  manage_master_user_password   = true
  master_user_secret_kms_key_id = var.kms_key_arn

  db_subnet_group_name            = aws_db_subnet_group.this.name
  vpc_security_group_ids          = [aws_security_group.this.id]
  db_cluster_parameter_group_name = aws_rds_cluster_parameter_group.this.name

  storage_encrypted = true
  kms_key_id        = var.kms_key_arn

  backup_retention_period   = var.backup_retention_days
  preferred_backup_window   = "18:00-19:00" # UTC = 23:30 IST low-traffic
  copy_tags_to_snapshot     = true
  deletion_protection       = var.deletion_protection
  skip_final_snapshot       = false
  final_snapshot_identifier = "${var.name}-aurora-final"

  enabled_cloudwatch_logs_exports = ["postgresql"]

  serverlessv2_scaling_configuration {
    min_capacity = var.min_acu
    max_capacity = var.max_acu
  }

  tags = local.tags

  lifecycle {
    ignore_changes = [engine_version] # apply version upgrades deliberately, not on drift
  }
}

# Writer (index 0) + readers
resource "aws_rds_cluster_instance" "this" {
  count               = 1 + var.reader_count
  identifier          = "${var.name}-aurora-${count.index}"
  cluster_identifier  = aws_rds_cluster.this.id
  instance_class      = "db.serverless"
  engine              = aws_rds_cluster.this.engine
  engine_version      = aws_rds_cluster.this.engine_version
  db_subnet_group_name = aws_db_subnet_group.this.name

  performance_insights_enabled    = true
  performance_insights_kms_key_id = var.kms_key_arn
  monitoring_interval             = 60
  monitoring_role_arn             = aws_iam_role.monitoring.arn

  tags = merge(local.tags, { Role = count.index == 0 ? "writer" : "reader" })
}

# Enhanced monitoring role
data "aws_iam_policy_document" "monitoring_assume" {
  statement {
    actions = ["sts:AssumeRole"]
    principals {
      type        = "Service"
      identifiers = ["monitoring.rds.amazonaws.com"]
    }
  }
}

resource "aws_iam_role" "monitoring" {
  name               = "${var.name}-aurora-monitoring"
  assume_role_policy = data.aws_iam_policy_document.monitoring_assume.json
  tags               = local.tags
}

resource "aws_iam_role_policy_attachment" "monitoring" {
  role       = aws_iam_role.monitoring.name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AmazonRDSEnhancedMonitoringRole"
}
