-- 0009 · feature flags (Law 10). Default behaviour is OFF (a missing flag = off), so any
-- feature gated by @FeatureFlag must have an ENABLED row here to be reachable. Toggle
-- is_enabled=false for an instant kill-switch; use rollout_pct / rules.tenant_ids to stage.
INSERT INTO feature_flags (key, description, is_enabled, rollout_pct, rules) VALUES
  ('listing_boost', 'Paid listing visibility boosts', true, 100, '{}'),
  ('group_lots',    'FPO group-lot pooling',          true, 100, '{}'),
  ('audit_trail',   'Read-only audit-trail viewer for the tenant auditor role — OFF until enabled per tenant', false, 100, '{}'),
  ('ai_assistant',  'Governed farmer AI assistant (P1-13) — s2s ai-services inference + guardrails + cost caps; OFF until a model key is set', false, 100, '{}'),
  ('kyc',           'KYC document submission + review', true, 100, '{}'),
  ('product_batches','Regulated-input store inventory batches', true, 100, '{}'),
  ('online_payments','Online payment at checkout (wallet-service) — OFF until payments lands', false, 100, '{}'),
  ('commission_split','Split escrow into seller-net + commission + GST/TDS at settlement — OFF = full release', false, 100, '{}'),
  ('buyer_charges','Apply buyer-side charges (delivery slab + platform fee) at checkout — OFF = none', false, 100, '{}'),
  ('document_pdfs','Render + store statement/invoice PDFs to media — OFF = data only (no S3 write)', false, 100, '{}'),
  ('auctions','English/sealed auctions + bidding (EMD holds) — OFF until launch', false, 100, '{}'),
  ('offers','Buyer-seller price negotiation (offers/counters/accept) — OFF until launch', false, 100, '{}'),
  ('requirements','Reverse marketplace: demand posts + seller quotes — OFF until launch', false, 100, '{}'),
  ('logistics','Shipments + OTP-gated proof-of-delivery — OFF until launch', false, 100, '{}'),
  ('reviews','Verified-purchase ratings + moderation — OFF until launch', false, 100, '{}'),
  ('disputes','Order disputes + evidence + moderator resolution — OFF until launch', false, 100, '{}'),
  ('dispute_refunds','Wallet reversal (escrow → buyer) on a dispute refund — OFF until launch', false, 100, '{}'),
  ('promotions','Promotions + coupon codes (discount engine) — OFF until launch', false, 100, '{}'),
  ('memberships','Subscription tiers + wallet-paid memberships — OFF until launch', false, 100, '{}'),
  ('tenancy','SaaS plans + tenant subscriptions (quota foundation) — OFF until launch', false, 100, '{}'),
  ('labour','Labour bookings + assignments + wage settlement (dignity floor) — OFF until launch', false, 100, '{}'),
  ('livestock','Animal registry + vet marketplace + fee settlement — OFF until launch', false, 100, '{}'),
  ('dairy','Milk procurement: MCC/collections/rate-cards/bills + wallet payout — OFF until launch', false, 100, '{}'),
  ('equipment','Equipment/CHC rental: assets/rates/bookings + escrow settlement — OFF until launch', false, 100, '{}'),
  ('warehousing','Warehouse storage bookings + assays + eNWR + storage-fee settlement — OFF until launch', false, 100, '{}'),
  ('contract_farming','Contract farming: contracts + growers + input advances + grower settlement — OFF until launch', false, 100, '{}'),
  ('exports','Export compliance: exporter registrations + shipments + document checklist — OFF until launch', false, 100, '{}'),
  ('land_soil_weather','Land parcels + crop seasons + soil tests + weather advisory browse — OFF until launch', false, 100, '{}'),
  ('fintech','Agri-fintech lending: loan applications + disbursement + repayment (FPO lender) — OFF until launch', false, 100, '{}'),
  ('schemes','Government scheme applications + eligibility + observed DBT records — OFF until launch', false, 100, '{}'),
  ('services_marketplace','P2P service marketplace: offerings + bookings + fee settlement (customer→provider) — OFF until launch', false, 100, '{}'),
  ('communication','Notification spine: event catalog + templates + preferences + quiet hours + delivery log + domain-event fanout (external notifier) — OFF until launch', false, 100, '{}'),
  ('education','Agri-learning: instructors + courses + lessons + enrollment (free + paid wallet split) + progress — OFF until launch', false, 100, '{}'),
  ('ambassadors','Ambassador network: profiles + referrals + commission accrual + weekly wallet payout — OFF until launch', false, 100, '{}'),
  ('support','Helpdesk: support tickets + SLA + agent workflow + dispute auto-open — OFF until launch', false, 100, '{}'),
  ('cms','CMS: versioned content pages + scheduled banners — OFF until launch', false, 100, '{}'),
  ('market_intel','Mandi Pulse: mandi registry + price observations + fair-price bands + price alerts — OFF until launch', false, 100, '{}'),
  ('traceability','Farm-to-fork QR: trace lots + hash-chained journey + public scan — OFF until launch', false, 100, '{}'),
  ('ai_governance','AI governance: model registry (read) + inference audit log + human-in-the-loop review queue + content moderation reports — OFF until launch', false, 100, '{}'),
  ('search_indexing','OpenSearch projection: keep listings/products search indices in sync off the outbox — OFF = replica-backed search (kill switch; requires OPENSEARCH_URL)', false, 100, '{}'),
  ('bulk_import','Bulk CSV import: upload a CSV + apply it row-by-row through a registered applier (products/…) — OFF until launch', false, 100, '{}'),
  ('realtime_fanout','Realtime fan-out: mirror selected outbox events (auction bids, order status, MCC) to Redis Pub/Sub for the realtime-gateway WebSocket pods — OFF = clients poll (kill switch; requires REDIS_URL)', false, 100, '{}'),
  ('wage_priority_payout','Wage priority lane: on labour.wages_paid, promote a worker''s queued payouts into the fast wage lane so their bank disbursement jumps the bulk settlement queue — OFF = normal priority (kill switch)', false, 100, '{}')
ON CONFLICT (key) DO NOTHING;
