// core/media/media-links.service.ts
// MediaService — the upload/download lifecycle for media_assets:
//   requestUpload  → validate kind+mime+size → create a 'pending' asset → presigned PUT URL
//   confirmUpload  → record real bytes/sha/dims (owner-checked); scan_status stays 'pending'
//   handleScanResult (AV webhook, HMAC-verified) → set 'clean'/'infected'/'failed'
//   getDownloadUrl → presigned GET, ONLY when scan_status='clean' AND the caller may see it (404 else)
//   putGeneratedDocument → server-side upload of generated bytes (e.g. statement/invoice PDFs),
//                          recorded directly as a clean tenant 'document' (no client step)
// Fails closed: a file is never downloadable until the AV scan clears it.
import { createHmac, timingSafeEqual } from 'node:crypto';
import { Inject, Injectable } from '@nestjs/common';
import { UNIT_OF_WORK, UnitOfWork } from '../database/unit-of-work';
import { METRICS, Metrics, timed } from '../observability/metrics';
import { AppConfig } from '../config/app-config';
import { uuidv7 } from '../database/uuid.util';
import { BadRequestError } from '../../shared/errors/app-error';
import { ObjectStore } from './s3-presign.service';
import { MediaRepository } from './media.repository';
import { MediaKind, MEDIA_KINDS, isMimeAllowed, objectKey, parseObjectKey, MediaNotFoundError, UnsupportedMediaTypeError, MediaTooLargeError, MediaNotScannedError, ScanSignatureError } from './media.domain';
import { stripImageMetadata } from './image/exif-stripper';

export interface MediaActor { userId: string; canModerate: boolean; }
const SHA256_RE = /^[0-9a-f]{64}$/i;

@Injectable()
export class MediaService {
  constructor(
    @Inject(UNIT_OF_WORK) private readonly uow: UnitOfWork,
    @Inject(METRICS) private readonly metrics: Metrics,
    private readonly config: AppConfig,
    private readonly store: ObjectStore,
    private readonly repo: MediaRepository,
  ) {}

  async requestUpload(tenantId: string, userId: string, dto: { kind: MediaKind; mimeType: string; declaredBytes: number }) {
    if (!MEDIA_KINDS.includes(dto.kind)) throw new BadRequestError('invalid media kind');
    if (!isMimeAllowed(dto.kind, dto.mimeType)) throw new UnsupportedMediaTypeError(dto.mimeType);
    if (dto.declaredBytes <= 0 || dto.declaredBytes > this.config.media.maxUploadBytes) throw new MediaTooLargeError(this.config.media.maxUploadBytes);

    const id = uuidv7();
    const s3Key = objectKey(tenantId, dto.kind, id, dto.mimeType);
    await this.uow.run(tenantId, async (tx) => this.repo.insertPending(tx, { id, tenantId, uploaderUserId: userId, kind: dto.kind, s3Key, mimeType: dto.mimeType }), { userId });
    const uploadUrl = this.store.presignUpload(s3Key);
    this.metrics.inc('media.upload_requested', { tenant: tenantId, kind: dto.kind });
    return { mediaId: id, s3Key, uploadUrl, expiresInSec: this.config.media.presignExpirySec };
  }

  async confirmUpload(tenantId: string, actor: MediaActor, mediaId: string, dto: { bytes: number; sha256: string; width?: number; height?: number }) {
    if (!SHA256_RE.test(dto.sha256)) throw new BadRequestError('sha256 must be 64 hex chars');
    if (dto.bytes <= 0 || dto.bytes > this.config.media.maxUploadBytes) throw new MediaTooLargeError(this.config.media.maxUploadBytes);
    return this.uow.run(tenantId, async (tx) => {
      const m = await this.repo.getForUpdate(tx, tenantId, mediaId);
      if (!m || (m.uploaderUserId !== actor.userId && !actor.canModerate)) throw new MediaNotFoundError();   // 404 — no IDOR
      await this.repo.markUploaded(tx, tenantId, mediaId, { bytes: BigInt(dto.bytes), sha256: dto.sha256, width: dto.width ?? null, height: dto.height ?? null });
      return { mediaId, status: 'pending_scan' };
    }, { userId: actor.userId });
  }

  /** Presigned GET — only for a clean, visible asset. */
  async getDownloadUrl(tenantId: string, actor: MediaActor, mediaId: string) {
    return timed(this.metrics, 'media.download_url', { tenant: tenantId }, async () => {
      const m = await this.repo.getVisible(tenantId, mediaId, actor.userId, actor.canModerate);
      if (!m) throw new MediaNotFoundError();
      if (m.scanStatus !== 'clean') throw new MediaNotScannedError(m.scanStatus);
      return { mediaId, url: this.store.presignDownload(m.s3Key), expiresInSec: this.config.media.presignExpirySec };
    });
  }

  /** AV scan-result webhook (unauthenticated → HMAC-verified). The s3 key carries the tenant+id. */
  async handleScanResult(rawBody: string, signature: string) {
    const secret = this.config.media.scanSecret;
    if (!secret) throw new ScanSignatureError();                 // fail closed if not configured
    const expected = createHmac('sha256', secret).update(rawBody).digest('hex');
    const a = Buffer.from(expected); const b = Buffer.from(signature ?? '');
    if (a.length !== b.length || !timingSafeEqual(a, b)) throw new ScanSignatureError();

    const p = JSON.parse(rawBody) as { s3_key?: string; status?: string };
    const status = p.status === 'clean' ? 'clean' : p.status === 'infected' ? 'infected' : 'failed';
    const parsed = p.s3_key ? parseObjectKey(p.s3_key) : null;
    if (!parsed) throw new BadRequestError('unresolvable s3_key');
    await this.uow.run(parsed.tenantId ?? '', async (tx) => this.repo.setScanStatus(tx, parsed.tenantId, parsed.mediaId, status), { userId: 'system' });
    this.metrics.inc('media.scan_result', { status });
    return { ok: true };
  }

  /** Strip privacy metadata (EXIF GPS / XMP) from a clean image, in place. Idempotent (exif_stripped
   *  flag). Runs in the EXIF-strip worker job after the AV scan clears the file. NOTE: this removes
   *  metadata only — pixel resize/thumbnail needs an image codec (deferred). */
  async processImage(tenantId: string, mediaId: string): Promise<{ stripped: boolean }> {
    const m = await this.uow.run(tenantId, async (tx) => this.repo.getForUpdate(tx, tenantId, mediaId), { userId: 'system' });
    if (!m || m.kind !== 'image' || m.scanStatus !== 'clean') return { stripped: false };
    const original = await this.store.getObject(m.s3Key);
    const { data, stripped } = stripImageMetadata(original, m.mimeType);
    if (stripped) await this.store.putObject(m.s3Key, data, m.mimeType);
    await this.uow.run(tenantId, async (tx) => this.repo.markExifStripped(tx, tenantId, mediaId), { userId: 'system' });
    this.metrics.inc('media.exif_processed', { tenant: tenantId, stripped: String(stripped) });
    return { stripped };
  }

  /** Server-generated document (e.g. a settlement statement / GST invoice PDF): upload + record
   *  as a clean tenant document. Returns the media id to store as pdf_media_id. */
  async putGeneratedDocument(tenantId: string, body: Buffer, mimeType = 'application/pdf'): Promise<string> {
    const id = uuidv7();
    const kind: MediaKind = 'document';
    const s3Key = objectKey(tenantId, kind, id, mimeType);
    await this.store.putObject(s3Key, body, mimeType);           // resilience-wrapped network PUT
    await this.uow.run(tenantId, async (tx) => {
      await this.repo.insertPending(tx, { id, tenantId, uploaderUserId: 'system', kind, s3Key, mimeType });
      await this.repo.markUploaded(tx, tenantId, id, { bytes: BigInt(body.length), sha256: '', width: null, height: null });
      await this.repo.setScanStatus(tx, tenantId, id, 'clean');  // system-generated, no untrusted bytes
    }, { userId: 'system' });
    return id;
  }
}
