// core/media/s3-presign.service.ts
// ObjectStore — the S3 boundary. Presigning is LOCAL crypto (no network) so it needs no resilience;
// the server-side putObject (used for generated PDFs) is a real network PUT and IS wrapped in
// core/resilience. Config comes from AppConfig.media (bucket/region/creds/endpoint). Fails CLOSED:
// presign refuses if no bucket is configured (a misconfigured deploy can't hand out broken URLs).
import { Inject, Injectable } from '@nestjs/common';
import { AppConfig } from '../config/app-config';
import { ResilienceService } from '../resilience/resilience.service';
import { InfraError } from '../../shared/errors/app-error';
import { presignS3Url } from './s3/sigv4-presigner';

export const OBJECT_STORE = Symbol('OBJECT_STORE');

@Injectable()
export class ObjectStore {
  constructor(private readonly config: AppConfig, private readonly resilience: ResilienceService) {}

  private cfg() {
    const m = this.config.media;
    if (!m.bucket) throw new InfraError('MEDIA_NOT_CONFIGURED', 'object storage bucket is not configured');
    return m;
  }

  presignUpload(key: string, expiresSec?: number): string {
    const m = this.cfg();
    return presignS3Url({ method: 'PUT', region: m.region, bucket: m.bucket, key, accessKeyId: m.accessKeyId, secretAccessKey: m.secretAccessKey, endpoint: m.endpoint, forcePathStyle: m.forcePathStyle, expiresSec: expiresSec ?? m.presignExpirySec });
  }

  presignDownload(key: string, expiresSec?: number): string {
    const m = this.cfg();
    return presignS3Url({ method: 'GET', region: m.region, bucket: m.bucket, key, accessKeyId: m.accessKeyId, secretAccessKey: m.secretAccessKey, endpoint: m.endpoint, forcePathStyle: m.forcePathStyle, expiresSec: expiresSec ?? m.presignExpirySec });
  }

  /** Server-side upload of generated bytes (e.g. statement/invoice PDFs) via a short-lived signed
   *  PUT. Wrapped in resilience (timeout + circuit-breaker); not auto-retried as a money op would be. */
  async putObject(key: string, body: Buffer, contentType: string): Promise<void> {
    const url = this.presignUpload(key, 120);
    await this.resilience.run('s3', async () => {
      const res = await fetch(url, { method: 'PUT', headers: { 'content-type': contentType }, body: body as any });
      if (!res.ok) throw new InfraError('S3_PUT_FAILED', `S3 putObject failed (${res.status})`, { status: res.status });
    });
  }

  /** Server-side download of an object (e.g. for the EXIF-strip job). Resilience-wrapped. */
  async getObject(key: string): Promise<Buffer> {
    const url = this.presignDownload(key, 120);
    return this.resilience.run('s3', async () => {
      const res = await fetch(url, { method: 'GET' });
      if (!res.ok) throw new InfraError('S3_GET_FAILED', `S3 getObject failed (${res.status})`, { status: res.status });
      return Buffer.from(await res.arrayBuffer());
    });
  }
}
